web:
  image: shreyansh97/express-load-balancer:latest
  ports:
    - 9582:9582
    - 80:80
    - 443:443
  environment:
    - USERNAME=admin
    - PASSWORD=admin
    - NODE_ENV=production
  command: /bin/bash -c "npm run prod && nginx -g 'daemon off;'"
  